backend:
  name: git-gateway
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicaci칩n', name: 'date', widget: 'datetime' }
      - { label: 'Sede', name: 'tags', widget: 'select', options: [{ label: "Comisi칩n Directiva", value: "acomisiondirectiva" },{ label: "Buenos Aires", value: "buenosaires" },{ label: "Chaco", value: "chaco" },{ label: "C칩rdoba", value: "cordoba" },{ label: "Corrientes", value: "corrientes" },{ label: "Mendoza", value: "mendoza" },{ label: "Rosario", value: "rosario" },{ label: "Salta", value: "salta" },{ label: "San Juan", value: "sanjuan" },{ label: "Tucuma치n", value: "tucuman" }] }
      - { label: 'Autor', name: 'author', widget: 'string' }
      - { label: 'Publicado', name: 'published', widget: 'boolean', default: true }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }